#!/bin/bash

#TODO(skishore): Get the code to compile with -Wsign-conversion.
CC="emcc -O2 -fno-exceptions -fno-rtti -mnontrapping-fptoint -sALLOW_MEMORY_GROWTH -sENVIRONMENT=web -sFILESYSTEM=0 -sWASM=1 -Wl,--export=malloc -Wl,--export=free -Wall -Wconversion -Werror -Wno-sign-conversion -g2"
TARGET=core

set -ex

$CC wasm/*.cpp -o "$TARGET.js"

echo "" >> "$TARGET.js"
echo "__ATPOSTRUN__.push(() => window.onWasmCompile(Module));" >> "$TARGET.js"
sed -i '' 's/var asm = createWasm/window.beforeWasmCompile(wasmImports); var asm = createWasm/g' "$TARGET.js"
stat -f '%z' "$TARGET.wasm"
